package com.argumentor.app.data.export

import android.content.Context
import com.argumentor.app.R
import com.argumentor.app.data.model.*
import com.google.common.truth.Truth.assertThat
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.mockito.kotlin.*
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config
import java.io.ByteArrayOutputStream

@RunWith(RobolectricTestRunner::class)
@Config(manifest = Config.NONE, sdk = [34])
class MarkdownExporterTest {

    private lateinit var context: Context
    private lateinit var exporter: MarkdownExporter

    private val testTopic = Topic(
        id = "topic-1",
        title = "Test Topic Title",
        summary = "This is a test summary for the topic.",
        posture = Topic.Posture.NEUTRAL_CRITICAL,
        tags = listOf("tag1", "tag2"),
        createdAt = "2024-01-15T10:00:00Z",
        updatedAt = "2024-01-20T15:30:00Z"
    )

    private val testClaimPro = Claim(
        id = "claim-1",
        text = "This is a pro claim with supporting evidence for the argument.",
        stance = Claim.Stance.PRO,
        strength = Claim.Strength.HIGH,
        topics = listOf("topic-1")
    )

    private val testClaimCon = Claim(
        id = "claim-2",
        text = "This is a con claim against the argument being made here.",
        stance = Claim.Stance.CON,
        strength = Claim.Strength.MEDIUM,
        topics = listOf("topic-1")
    )

    private val testRebuttal = Rebuttal(
        id = "rebuttal-1",
        text = "This is a rebuttal to the claim that provides counter-argument.",
        claimId = "claim-1"
    )

    private val testEvidence = Evidence(
        id = "evidence-1",
        content = "Evidence content supporting the claim with data.",
        claimId = "claim-1",
        type = Evidence.EvidenceType.STUDY,
        quality = Evidence.Quality.HIGH,
        sourceId = "source-1"
    )

    private val testSource = Source(
        id = "source-1",
        title = "Test Source Title",
        url = "https://example.com/source",
        citation = "Author, A. (2024). Test Source.",
        date = "2024-01-10",
        notes = "Important research paper.",
        reliabilityScore = 0.85
    )

    private val testQuestion = Question(
        id = "question-1",
        text = "What evidence supports this claim?",
        targetId = "topic-1",
        kind = Question.QuestionKind.EVIDENCE
    )

    @Before
    fun setup() {
        context = mock()
        setupStringResources()
        exporter = MarkdownExporter(context)
    }

    private fun setupStringResources() {
        whenever(context.getString(R.string.export_posture_label)).thenReturn("Posture:")
        whenever(context.getString(R.string.export_created_label)).thenReturn("Created:")
        whenever(context.getString(R.string.export_updated_label)).thenReturn("Updated:")
        whenever(context.getString(R.string.export_tags_label)).thenReturn("Tags:")
        whenever(context.getString(R.string.export_summary_label)).thenReturn("Summary")
        whenever(context.getString(R.string.export_arguments_label)).thenReturn("Arguments")
        whenever(context.getString(R.string.export_position_label)).thenReturn("Position:")
        whenever(context.getString(R.string.export_strength_label)).thenReturn("Strength:")
        whenever(context.getString(R.string.export_evidence_label)).thenReturn("Evidence:")
        whenever(context.getString(R.string.export_source_label)).thenReturn("Source:")
        whenever(context.getString(R.string.export_rebuttals_label)).thenReturn("Rebuttals:")
        whenever(context.getString(R.string.export_questions_label)).thenReturn("Questions")
        whenever(context.getString(R.string.export_sources_label)).thenReturn("Sources")
        whenever(context.getString(R.string.export_citation_label)).thenReturn("Citation:")
        whenever(context.getString(R.string.export_url_label)).thenReturn("URL:")
        whenever(context.getString(R.string.export_date_label)).thenReturn("Date:")
        whenever(context.getString(R.string.export_reliability_label)).thenReturn("Reliability:")
        whenever(context.getString(eq(R.string.export_generated_by), any())).thenAnswer { invocation ->
            "Generated by ArguMentor on ${invocation.arguments[1]}"
        }
        whenever(context.getString(R.string.export_multiple_topics_title)).thenReturn("Topics Export")
        whenever(context.getString(eq(R.string.export_exported_label), any())).thenAnswer { invocation ->
            "Exported on ${invocation.arguments[1]}"
        }
        whenever(context.getString(eq(R.string.export_and_more), any())).thenAnswer { invocation ->
            "and ${invocation.arguments[1]} more..."
        }
    }

    @Test
    fun `exportTopicToMarkdown returns success with valid data`() {
        val outputStream = ByteArrayOutputStream()

        val result = exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = listOf(testClaimPro, testClaimCon),
            rebuttals = mapOf("claim-1" to listOf(testRebuttal)),
            evidence = mapOf("claim-1" to listOf(testEvidence)),
            questions = listOf(testQuestion),
            sources = mapOf("source-1" to testSource),
            outputStream = outputStream
        )

        assertThat(result.isSuccess).isTrue()
    }

    @Test
    fun `exportTopicToMarkdown writes topic title as H1`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("# Test Topic Title")
    }

    @Test
    fun `exportTopicToMarkdown includes posture`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("**Posture:**")
        assertThat(markdown).contains("NEUTRAL CRITICAL")
    }

    @Test
    fun `exportTopicToMarkdown includes tags`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("**Tags:**")
        assertThat(markdown).contains("`tag1`")
        assertThat(markdown).contains("`tag2`")
    }

    @Test
    fun `exportTopicToMarkdown excludes tags section when no tags`() {
        val topicWithoutTags = testTopic.copy(tags = emptyList())
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = topicWithoutTags,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).doesNotContain("**Tags:**")
    }

    @Test
    fun `exportTopicToMarkdown includes summary section`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("## Summary")
        assertThat(markdown).contains("This is a test summary for the topic.")
    }

    @Test
    fun `exportTopicToMarkdown includes claims with stance icons`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = listOf(testClaimPro, testClaimCon),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("## Arguments")
        assertThat(markdown).contains("✅") // PRO icon
        assertThat(markdown).contains("❌") // CON icon
    }

    @Test
    fun `exportTopicToMarkdown includes claim stance and strength`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = listOf(testClaimPro),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("**Position:** PRO")
        assertThat(markdown).contains("**Strength:** HIGH")
    }

    @Test
    fun `exportTopicToMarkdown includes evidence for claims`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = listOf(testClaimPro),
            rebuttals = emptyMap(),
            evidence = mapOf("claim-1" to listOf(testEvidence)),
            questions = emptyList(),
            sources = mapOf("source-1" to testSource),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("**Evidence:**")
        assertThat(markdown).contains("(STUDY)")
        assertThat(markdown).contains("Evidence content supporting the claim")
        assertThat(markdown).contains("*Source: Test Source Title*")
    }

    @Test
    fun `exportTopicToMarkdown includes rebuttals for claims`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = listOf(testClaimPro),
            rebuttals = mapOf("claim-1" to listOf(testRebuttal)),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("**Rebuttals:**")
        assertThat(markdown).contains("↳")
        assertThat(markdown).contains("This is a rebuttal to the claim")
    }

    @Test
    fun `exportTopicToMarkdown includes questions section`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = listOf(testQuestion),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("## Questions")
        assertThat(markdown).contains("- What evidence supports this claim?")
    }

    @Test
    fun `exportTopicToMarkdown excludes questions section when no questions`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).doesNotContain("## Questions")
    }

    @Test
    fun `exportTopicToMarkdown includes sources section with all fields`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = mapOf("source-1" to testSource),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("## Sources")
        assertThat(markdown).contains("### Test Source Title")
        assertThat(markdown).contains("**Citation:**")
        assertThat(markdown).contains("**URL:**")
        assertThat(markdown).contains("[https://example.com/source]")
        assertThat(markdown).contains("**Date:**")
        assertThat(markdown).contains("**Reliability:** 85%")
        assertThat(markdown).contains("Important research paper.")
    }

    @Test
    fun `exportTopicToMarkdown includes footer with generation timestamp`() {
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("*Generated by ArguMentor on")
    }

    @Test
    fun `exportTopicToMarkdown handles exception and returns failure`() {
        val failingStream = mock<java.io.OutputStream>()
        whenever(failingStream.write(any<ByteArray>())).thenThrow(java.io.IOException("Write failed"))

        val result = exporter.exportTopicToMarkdown(
            topic = testTopic,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = failingStream
        )

        assertThat(result.isFailure).isTrue()
    }

    @Test
    fun `exportMultipleTopicsToMarkdown returns success`() {
        val outputStream = ByteArrayOutputStream()

        val result = exporter.exportMultipleTopicsToMarkdown(
            topics = listOf(testTopic),
            claimsMap = mapOf("topic-1" to listOf(testClaimPro)),
            outputStream = outputStream
        )

        assertThat(result.isSuccess).isTrue()
    }

    @Test
    fun `exportMultipleTopicsToMarkdown includes all topics`() {
        val topic2 = testTopic.copy(id = "topic-2", title = "Second Topic")
        val outputStream = ByteArrayOutputStream()

        exporter.exportMultipleTopicsToMarkdown(
            topics = listOf(testTopic, topic2),
            claimsMap = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("## Test Topic Title")
        assertThat(markdown).contains("## Second Topic")
    }

    @Test
    fun `exportMultipleTopicsToMarkdown shows claim count and first 3 claims`() {
        val claims = listOf(
            testClaimPro,
            testClaimCon,
            testClaimPro.copy(id = "claim-3", text = "Third claim text"),
            testClaimCon.copy(id = "claim-4", text = "Fourth claim text")
        )
        val outputStream = ByteArrayOutputStream()

        exporter.exportMultipleTopicsToMarkdown(
            topics = listOf(testTopic),
            claimsMap = mapOf("topic-1" to claims),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("**Arguments** 4")
        assertThat(markdown).contains("and 1 more...")
    }

    @Test
    fun `exported markdown is valid UTF-8`() {
        val topicWithUnicode = testTopic.copy(
            title = "Sujet avec accents éàü",
            summary = "Résumé avec caractères spéciaux: ñ, ø, ß"
        )
        val outputStream = ByteArrayOutputStream()

        exporter.exportTopicToMarkdown(
            topic = topicWithUnicode,
            claims = emptyList(),
            rebuttals = emptyMap(),
            evidence = emptyMap(),
            questions = emptyList(),
            sources = emptyMap(),
            outputStream = outputStream
        )

        val markdown = outputStream.toString(Charsets.UTF_8)
        assertThat(markdown).contains("éàü")
        assertThat(markdown).contains("ñ, ø, ß")
    }
}
